- charts/charts/tenant-namespace/values.yaml
Fixed location of rbac.scope for ingress
Removed stats as it was removed in nginx-ingress chart v1.14.0
Fixed default extraQuota value
> [tenant-namespace] Cleaned up values file

- charts/charts/kubeupdater/Chart.yaml
Bumped kubeupdater chart version after PR #11.
> [kubeupdater] Bumped kubeupdater chart version

- charts/charts/tenant-namespace/requirements.yaml
Fixes build issue due to missing repository.
> Updated tenant-namespace stable url

- .github/workflows/main.yml
- charts/charts/buildall
- charts/image-library-charts/buildall
> GitHub Actions Workflow

- containers/tenant-namespace-operator/Dockerfile
- containers/tenant-namespace-operator/roles/tenantnamespace/tasks/main.yml
I think this PR still needs version bumps.
> [tenant-namespace-operator] Track Load Balancer IP addresses

- charts/charts/tenant-namespace/templates/nginx-ingress-role.yaml
- charts/charts/tenant-namespace/templates/nginx-ingress-rolebinding.yaml
Updated ingress role based on upstream chart
Quoted namespace in rolebinding
> [tenant-namespace] Updated tenant-namespace ingress resources

- charts/charts/tenant-namespace-operator/Chart.yaml
- charts/charts/tenant-namespace-operator/templates/clusterrole.yaml
- containers/tenant-namespace-operator/Dockerfile
- containers/tenant-namespace-operator/buildenv
- containers/tenant-namespace-operator/roles/tenantnamespace/tasks/main.yml
- Added immutable resource removal
- Added ingressclasses permissions
- Bumped versions
> [tenant-namespace-operator] Updated for new tenant-namespace

- .github/workflows/main.yml
- charts/charts/buildall
- charts/image-library-charts/buildall
This conflicts a bit with the rpms-docker PR as both touch builds for rpms.  One of these PRs will require changes after the other is merged
> Added k8s 1.21 image and charts

- charts/charts/tenant-namespace-operator/Chart.yaml
- containers/tenant-namespace-operator/Dockerfile
- containers/tenant-namespace-operator/buildenv
- containers/tenant-namespace-operator/configmap.patch
- containers/tenant-namespace-operator/requirements.yml
- containers/tenant-namespace-operator/roles/tenantnamespace/tasks/main.yml
Upgraded tenant-namespace chart version
Handled new version of ingress-nginx
Added ingress-nginx patch to fix configmap regression
Added extra namespace labels and annotations support
> Upgraded tenant-namespace-operator

- charts/charts/k8s-node-image/templates/ingress.yaml
- charts/charts/k8s-node-image/values.yaml
Now supports later ingress api versions
I used the yaml from helm create as an example to update this ingress.
> Updated node-image ingress

- charts/charts/buildall
- charts/charts/k8s-node-image/.helmignore
- charts/charts/k8s-node-image/Chart.yaml
- charts/charts/k8s-node-image/requirements.yaml
- charts/charts/k8s-node-image/templates/_helpers.tpl
- charts/charts/k8s-node-image/templates/anaconda-deployment.yaml
- charts/charts/k8s-node-image/templates/anaconda-pdb.yaml
- charts/charts/k8s-node-image/templates/anaconda-service.yaml
- charts/charts/k8s-node-image/templates/ingress.yaml
- charts/charts/k8s-node-image/templates/k8s-node-deployment.yaml
- charts/charts/k8s-node-image/templates/k8s-node-pdb.yaml
- charts/charts/k8s-node-image/templates/k8s-node-service.yaml
- charts/charts/k8s-node-image/values.yaml
Upgraded to v2 Chart
Moved standard labels to helpers
Added image pull secrets
Added pod annotations
> [k8s-node-image] Added PDBs

- charts/charts/tenant-namespace-operator/Chart.yaml
- charts/charts/tenant-namespace-operator/templates/deployment.yaml
- charts/charts/tenant-namespace-operator/templates/ic-clusterrole.yaml
- charts/charts/tenant-namespace-operator/templates/ingressclass.yaml
- charts/charts/tenant-namespace-operator/values.yaml
- containers/tenant-namespace-operator/Dockerfile
- containers/tenant-namespace-operator/buildenv
- containers/tenant-namespace-operator/roles/tenantnamespace/tasks/main.yml
Upgrade tenant-namespace-operator to use the new version of the tenant-namespace chart
> Upgrade tenant-namespace-operator 

- containers/anaconda-nginx9/Dockerfile
- containers/anaconda-nginx9/buildenv
- containers/anaconda9/Dockerfile
- containers/anaconda9/buildenv
- containers/k8s-node-image-nginx9/Dockerfile
- containers/k8s-node-image-nginx9/buildenv
- containers/k8s-node-image9/Dockerfile
- containers/k8s-node-image9/buildenv
- containers/rpms-containerd9/Dockerfile
- containers/rpms-containerd9/buildenv
- containers/rpms-containerd9/docker-ce.repo
- containers/rpms-kubernetes9/Dockerfile
- containers/rpms-kubernetes9/buildenv
- containers/rpms-kubernetes9/kubernetes.repo
- containers/rpms-node-base9/Dockerfile
- containers/rpms-node-base9/buildenv
- containers/rpms-openvswitch9/Dockerfile
- containers/rpms-openvswitch9/buildenv
This PR is the first stab at making containers with a Rocky 9 base.
> Rocky 9 based images

- containers/rpms-node-base9/Dockerfile
* Switched to dnf install for better dependency resolution
* Removed Base/Anaconda Tools as they are not needed
* Switched to released dockerfile frontend with mount type secret support
> Fixed issues with nfs-utils & sssd-common packages

- charts/charts/tenant-namespace-operator/Chart.yaml
- charts/charts/tenant-namespace-operator/templates/role.yaml
Prometheus rules can be created from the ingress chart
> [tenant-namespace-operator] Added support for prometheus rules in the role

- .github/workflows/main.yml
K8s package repo is going away
Current repo images will remain
> Stopped building kube rpm repos for Centos 7

- charts/charts/tenant-namespace-operator/Chart.yaml
- containers/tenant-namespace-operator/buildenv
- containers/tenant-namespace-operator/roles/tenantnamespace/tasks/main.yml
Added user/admin specific labels and annotations
Switched to using our values merge system for labels/annotations
Fixed flavor not contributing to labels/annotations
> [tenant-namespace-operator] Added more label/annotation settings

- charts/charts/tenant-namespace-operator/templates/deployment.yaml
- charts/charts/tenant-namespace-operator/values.yaml
Added debug logs option
Added log verbosity
Added max concurrent reconciles
> [tenant-namespace-operator] Added operator env config items

- .github/workflows/main.yml
1.30 was being treated as a number and coverted to 1.3
> Quoted kube version matrix entries

- charts/charts/k8s-node-image9/values.yaml
> [k8s-node-image9] Fixed parent refs default value

- charts/charts/tenant-namespace/Chart.yaml
- charts/charts/tenant-namespace/templates/gateway.yaml
- charts/charts/tenant-namespace/values.yaml
Allows setting up gateway api instead of ingress
> [tenant-namespace] Added gateway resource

- charts/charts/tenant-namespace-operator/Chart.yaml
- charts/charts/tenant-namespace-operator/templates/deployment.yaml
- charts/charts/tenant-namespace-operator/values.yaml
- containers/tenant-namespace-operator/Dockerfile
- containers/tenant-namespace-operator/buildenv
- containers/tenant-namespace-operator/watches.yaml
* Upgraded to new tenant-namespace chart with rolled back ingress
* Pushed reconcilePeriod to 1 hour
* Lowered the max number of ansible runner artifacts
* Added runner dir as tmpfs options to chart
> [tenant-namespace-operator] Fixed operator issues

- containers/xmlstarlet/Dockerfile
Now executes xmlstarlet directly
> [xmlstarlet] Fixed xmlstarlet entrypoint

- charts/charts/buildall
- charts/image-library-charts/buildall
* Fixes issues with removed mirror content
> Removed refs to centos chart builds
